### ISSUE TITLE
Error :econnrefused

### ISSUE THREAD

**Issue by hirocaster** [hirocaster/ratchet_wrench#6]
Encountered at stress test.

```
16:03:08.968 [error] ** (RatchetWrench.Exception.APIRequestError) Request API error. client: :econnrefused
    (ratchet_wrench 0.3.1) lib/ratchet_wrench.ex:132: RatchetWrench.request_api_error/1
    (ratchet_wrench 0.3.1) lib/ratchet_wrench/transaction_manager.ex:33: RatchetWrench.TransactionManager.begin_transaction/0
    (ratchet_wrench 0.3.1) lib/ratchet_wrench/transaction_manager.ex:21: RatchetWrench.TransactionManager.begin/0
    (ratchet_wrench 0.3.1) lib/ratchet_wrench.ex:242: RatchetWrench.transaction/2
    (ratchet_wrench 0.3.1) lib/ratchet_wrench/repo.ex:257: RatchetWrench.Repo.insert/1
    test/ratchet_wrench_test.exs:446: anonymous fn/0 in RatchetWrenchTest."test Stress test for transaction was aboarted."/1
    (elixir 1.10.3) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.10.3) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.12.1) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

**Comment by hirocaster** [comment]
ref: https://github.com/teamon/tesla/blob/9ea2e9e663b6ec3ca1acad7178a863b76da0cab9/lib/tesla/adapter/httpc.ex#L101
